export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';


export const GET_PANTRY_ITEMS = 'GET_PANTRY_ITEMS';
export const GET_MEALS = 'GET_MEALS';

export const FRIDGE_ITEMS_LOADING = 'FRIDGE_ITEMS_LOADING';
export const GET_FRIDGE_ITEMS = 'GET_FRIDGE_ITEMS';
export const ADD_ITEM_TO_FRIDGE = 'ADD_ITEM_TO_FRIDGE';