export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';

export const FRIDGE_ITEMS_LOADING = 'FRIDGE_ITEMS_LOADING';
export const GET_FRIDGE_ITEMS = 'GET_FRIDGE_ITEMS';
export const ADD_ITEM_TO_FRIDGE = 'ADD_ITEM_TO_FRIDGE';
export const DELETE_ITEM_FROM_FRIDGE = 'DELETE_ITEM_FROM_FRIDGE';
export const DELETE_FRIDGE = 'DELETE_FRIDGE';

export const PANTRY_ITEMS_LOADING = 'PANTRY_ITEMS_LOADING';
export const GET_PANTRY_ITEMS = 'GET_PANTRY_ITEMS';
export const ADD_ITEM_TO_PANTRY = 'ADD_ITEM_TO_PANTRY';
export const DELETE_ITEM_FROM_PANTRY = 'DELETE_ITEM_FROM_PANTRY';

export const MEALS_LOADING = 'MEALS_LOADING';
export const MEAL_ITEMS_LOADING = 'MEAL_ITEMS_LOADING';
export const GET_MEALS = 'GET_MEALS';
export const GET_MEAL_ITEMS = 'GET_MEAL_ITEMS';
export const ADD_MEAL = 'ADD_MEAL';
export const ADD_ITEM_TO_MEAL = 'ADD_ITEM_TO_MEAL';
export const DELETE_ITEM_FROM_MEAL = 'DELETE_ITEM_FROM_MEAL';
export const DELETE_MEAL = 'DELETE_MEAL';

export const ADD_ITEM_SHOPPING_LIST = 'ADD_ITEM_SHOPPING_LIST';
export const GET_SHOPPINGLIST_ITEMS = 'GET_SHOPPINGLIST_ITEMS'


